### ISSUE TITLE
Kernel build error

### ISSUE THREAD

**Issue by mhc0009** [mohammad92/android_kernel_samsung_sm8450#1]
Hi

I tried build_menu to build kernel, but got the following error:
:
  HDRINST usr/include/asm/shmbuf.h
  HDRINST usr/include/asm/types.h
  HDRINST usr/include/asm/ipcbuf.h
  HDRINST usr/include/asm/termios.h
  HDRINST usr/include/asm/poll.h
make[1]: Leaving directory '/home/me/work_area/sam/avg6/srx/K2/out'
make: *** [Makefile:185: __sub-make] Error 2
make: Leaving directory '/home/me/work_area/sam/avg6/srx/K2'
Kernel STUCK in BUILD!, Press [Enter] key to return to Main menu...

Could u advise what is the most probable cause or if I had missed something b4 using the build_menu

Thanks
Regards
Chow

**Comment by mohammad92** [comment]
This log doesnt help, if you are using laptop use thin LTO instead
